<?php
    session_start();
    require_once ('../assets/tcpdf/tcpdf.php');
    class MYPDF extends TCPDF {
        public function Footer(){
            $firstname= $_SESSION['firstname'];
            $lastname= $_SESSION['lastname'];
            $this -> SetY(-15);
            $this -> SetFont('Helvetica', 'BI', 10);
            $this -> Cell(0, 10, 'Generated by: '.$firstname,  0, false, 'L', 0, '', 0, false, 'T', 'M');
            $this -> SetY(-15);
            $this -> SetFont('Helvetica', 'I', 10);
            $this -> Cell(0, 10, 'Page ' .$this-> getAliasNumPage(), 0, false, 'R', 0, '', 0, false, 'T', 'M');
        }
    }
    function fetch_data() {
		$output = '';
        $table_name = $_POST['doc_type'];
		  $category = $_POST['category'];
		   $doc_type = $_POST['doc_type'];
		 $doc_name = $_POST['doc_name'];
		 $datefilter = $_POST['datefilter'];
		 $string=$datefilter;
				$last_space = strrpos($string, ' ');
				$last_word = substr($string, $last_space);
				$first_chunk = substr($string, 0, $last_space - 2);
			$date_to = date('Y-m-d', strtotime($last_word));
			$date_to_temp = date('d F Y', strtotime($date_to));
			$date_from_temp = date('d F Y', strtotime($first_chunk));
	$date_from = date('Y-m-d', strtotime($first_chunk));
        $client = $_POST['client_id'];
        $service_by = $_POST['service_by'];
		$report_name= $_POST['report_name'];
			$total = 0;
		$percentage =0;
		  $count = 0;
			
			// PMS
		require '../inc/dbc.inc.php';
			
        if ($table_name == "res_pms") {
			$sql1 = "SELECT * FROM schedule where schedule.schedule_date BETWEEN '$date_from' and '$date_to' AND schedule.contract_id !='' ";  
				 $result1 = mysqli_query($conn, $sql1);  
                while($row1 = mysqli_fetch_array($result1)) {
				$total++; 
				}
		if ($category == "Attended") {
            if ($client == "null" &&   $service_by == "null") {
                $sql = "SELECT pms.schedule_id, pms.service_date, pms.service_by, schedule.schedule_date, schedule.client_id, schedule.model, clients.client_name, clients.client_address, machine_type.machine_name from (((pms inner join schedule on pms.schedule_id = schedule.schedule_id) left join clients on schedule.client_id = clients.client_id)
				left join machine_type on schedule.machine_type = machine_type.machine_id) where schedule.schedule_date BETWEEN '$date_from' and '$date_to' AND schedule.contract_id !='' GROUP BY pms.schedule_id";  
				 $result = mysqli_query($conn, $sql);  
                while($row = mysqli_fetch_array($result)) {
					$count++;
                    $output .= 
                    '<tr align="center">  
                        <td>'.$row['client_name'].'</td>  
                        <td>'.$row['client_address'].'</td> 
						<td>'.$row['machine_name'].' - '.$row['model'].'</td>						
                 <td>'.date('d F Y', strtotime($row['schedule_date'])).'</td>  
				  <td>'.date('d F Y', strtotime($row['service_date'])).'</td>  
                        <td>'.$row['service_by'].'</td>
                     
                    </tr>';  
                }
					if($total > 0 && $output !='') {
					$output .= '<br><br>Attended ';
		$percentage  = ($count / $total)  * 100;
			$output.=$doc_name.': '.(int)$percentage.'%';

        }
            } elseif ($client != "null" && $service_by !="null") {
                $sql = "SELECT pms.schedule_id, pms.service_date, pms.service_by, schedule.schedule_date, schedule.client_id, schedule.model, clients.client_name, clients.client_address, machine_type.machine_name from (((pms inner join schedule on pms.schedule_id = schedule.schedule_id) left join clients on schedule.client_id = clients.client_id)
				left join machine_type on schedule.machine_type = machine_type.machine_id)where schedule.schedule_date  BETWEEN '$date_from' and '$date_to' AND schedule.contract_id !='' and clients.client_id = '$client' and pms.service_by = '$service_by' GROUP BY pms.schedule_id";  
                $result = mysqli_query($conn, $sql);  
                while($row = mysqli_fetch_array($result)) {
					$count++;
                    $output .= 
                   '<tr align="center">  
                         <td>'.$row['client_name'].'</td>  
                        <td>'.$row['client_address'].'</td> 
				<td>'.$row['machine_name'].' - '.$row['model'].'</td>						
                       <td>'.date('d F Y', strtotime($row['schedule_date'])).'</td>  
				  <td>'.date('d F Y', strtotime($row['service_date'])).'</td>  
                        <td>'.$row['service_by'].'</td>
                    </tr>'; 
                }
            }
			elseif ($client != "null" && $service_by =="null") {
                $sql = "SELECT pms.schedule_id, pms.service_date, pms.service_by, schedule.schedule_date, schedule.client_id, schedule.model, clients.client_name, clients.client_address, machine_type.machine_name from (((pms inner join schedule on pms.schedule_id = schedule.schedule_id) left join clients on schedule.client_id = clients.client_id)
				left join machine_type on schedule.machine_type = machine_type.machine_id)where schedule.schedule_date  BETWEEN '$date_from' and '$date_to' AND schedule.contract_id !='' and clients.client_id = '$client' GROUP BY pms.schedule_id ";  
                $result = mysqli_query($conn, $sql);  
                while($row = mysqli_fetch_array($result)) {
					$count++;
                    $output .= 
                   '<tr align="center">  
                         <td>'.$row['client_name'].'</td>  
                        <td>'.$row['client_address'].'</td> 
						<td>'.$row['machine_name'].' - '.$row['model'].'</td>						
                   <td>'.date('d F Y', strtotime($row['schedule_date'])).'</td>  
				  <td>'.date('d F Y', strtotime($row['service_date'])).'</td>  
                        <td>'.$row['service_by'].'</td>
                    </tr>'; 
                }
            }
			elseif ($client == "null" && $service_by !="null") {
                $sql = "SELECT pms.schedule_id, pms.service_date, pms.service_by, schedule.schedule_date, schedule.client_id, schedule.model, clients.client_name, clients.client_address, machine_type.machine_name from (((pms inner join schedule on pms.schedule_id = schedule.schedule_id) left join clients on schedule.client_id = clients.client_id)
				left join machine_type on schedule.machine_type = machine_type.machine_id) where schedule.schedule_date  BETWEEN '$date_from' and '$date_to' AND schedule.contract_id !='' and pms.service_by = '$service_by' GROUP BY pms.schedule_id";  
                $result = mysqli_query($conn, $sql);  
                while($row = mysqli_fetch_array($result)) {
					$count++;
                    $output .= 
                   '<tr align="center">  
                         <td>'.$row['client_name'].'</td>  
                        <td>'.$row['client_address'].'</td> 
					<td>'.$row['machine_name'].' - '.$row['model'].'</td>					
                  <td>'.date('d F Y', strtotime($row['schedule_date'])).'</td>  
				  <td>'.date('d F Y', strtotime($row['service_date'])).'</td>  
                        <td>'.$row['service_by'].'</td>
                    </tr>'; 
                }
            }
		
		}
		elseif ($category == "Unattended") {
            if ($client == "null" &&   $service_by == "null") {
                $sql = "select schedule.schedule_id, schedule.model, schedule.schedule_date, machine_type.machine_name, clients.client_name, clients.client_address from ((schedule left join clients on schedule.client_id = clients.client_id )
				left join machine_type on schedule.machine_type = machine_type.machine_id) where  schedule.schedule_date BETWEEN '$date_from' and '$date_to' and schedule.contract_id !='' and schedule.status !='2'  ";  
				 $result = mysqli_query($conn, $sql);  
                while($row = mysqli_fetch_array($result)) {
					$count++;
                    $output .= 
                    '<tr align="center">  
                        <td>'.$row['client_name'].'</td>  
                        <td>'.$row['client_address'].'</td> 
						<td>'.$row['machine_name'].' - '.$row['model'].'</td>						
                      <td>'.date('d F Y', strtotime($row['schedule_date'])).'</td>  
                       
                     
                    </tr>';  
                }
			
            } elseif ($client != "null" && $service_by !="null") {
                $sql = "select schedule.schedule_id, schedule.model, schedule.schedule_date, machine_type.machine_name, clients.client_name, clients.client_address from ((schedule left join clients on schedule.client_id = clients.client_id )
				left join machine_type on schedule.machine_type = machine_type.machine_id) where  schedule.schedule_date BETWEEN '$date_from' and '$date_to' and schedule.contract_id !='' and schedule.status !='2'
				and clients.client_id = '$client' and pms.service_by = '$service_by'";  
                $result = mysqli_query($conn, $sql);  
                while($row = mysqli_fetch_array($result)) {
					$count++;
                    $output .= 
                   '<tr align="center">  
                         <td>'.$row['client_name'].'</td>  
                        <td>'.$row['client_address'].'</td> 
						<td>'.$row['machine_name'].' - '.$row['model'].'</td>					
                        <td>'.date('d F Y', strtotime($row['schedule_date'])).'</td>  
                    
                    </tr>'; 
                }
            }
			elseif ($client != "null" && $service_by =="null") {
                $sql = "select schedule.schedule_id, schedule.model, schedule.schedule_date, machine_type.machine_name, clients.client_name, clients.client_address from ((schedule left join clients on schedule.client_id = clients.client_id )
				left join machine_type on schedule.machine_type = machine_type.machine_id)  where schedule.schedule_date  BETWEEN '$date_from' and '$date_to' AND schedule.contract_id !='' and clients.client_id = '$client' and schedule.status!='2' ";  
                $result = mysqli_query($conn, $sql);  
                while($row = mysqli_fetch_array($result)) {
					$count++;
                    $output .= 
                   '<tr align="center">  
                         <td>'.$row['client_name'].'</td>  
                        <td>'.$row['client_address'].'</td> 
						<td>'.$row['machine_name'].' - '.$row['model'].'</td>						
                        <td>'.date('d F Y', strtotime($row['schedule_date'])).'</td>  
                      
                    </tr>'; 
                }
            }
			elseif ($client == "null" && $service_by !="null") {
                $sql = "select schedule.schedule_id, schedule.model, schedule.schedule_date, machine_type.machine_name, clients.client_name, clients.client_address from ((schedule left join clients on schedule.client_id = clients.client_id )
				left join machine_type on schedule.machine_type = machine_type.machine_id)  where schedule.schedule_date  BETWEEN '$date_from' and '$date_to' AND schedule.contract_id !='' and pms.service_by = '$service_by'  and schedule.status !='2'";  
                $result = mysqli_query($conn, $sql);  
                while($row = mysqli_fetch_array($result)) {
					$count++;
                    $output .= 
                   '<tr align="center">  
                         <td>'.$row['client_name'].'</td>  
                        <td>'.$row['client_address'].'</td> 
						<td>'.$row['machine_name'].' - '.$row['model'].'</td>						
                        <td>'.date('d F Y', strtotime($row['schedule_date'])).'</td>   
                      
                    </tr>'; 
                }
            }
			
		}
		
		}
				
        //Service Call
       elseif ($table_name == "svc") {
		   $sql1 = "SELECT pms.schedule_id, pms.service_date, pms.service_by, schedule.schedule_date, schedule.client_id, schedule.model, clients.client_name, clients.client_address, machine_type.machine_name from (((pms inner join schedule on pms.schedule_id = schedule.schedule_id) left join clients on schedule.client_id = clients.client_id)
				left join machine_type on schedule.machine_type = machine_type.machine_id) where schedule.contract_id ='' GROUP BY pms.schedule_id";  
				 $result1 = mysqli_query($conn, $sql1);  
                while($row1 = mysqli_fetch_array($result1)) {
				$total++; 
				}
				if ($category == "Resolved" ){
		
            if ($client == "null" &&   $service_by == "null") {
				
                $sql = "SELECT pms.schedule_id, pms.service_date, pms.service_by, pms.status, schedule.schedule_date, schedule.model,  schedule.guest, schedule.rep_problem, schedule.client_id, clients.client_name, schedule.machine_type, schedule.model, clients.client_address, machine_type.machine_name from (((pms inner join schedule on pms.schedule_id = schedule.schedule_id) left join clients on schedule.client_id = clients.client_id)
				left join machine_type on schedule.machine_type = machine_type.machine_id) where pms.service_date BETWEEN '$date_from' and '$date_to' AND schedule.contract_id ='' and schedule.status = '2' GROUP BY pms.schedule_id";  
                $result = mysqli_query($conn, $sql);  
                while($row = mysqli_fetch_array($result)) {
						 if ($row['guest']) {
		$guest = $row['guest'];
		 $last_space = strrpos($guest, ' / ');
$clientAddress = substr($guest, $last_space + 2);
$clientName = substr($guest, 0, $last_space);
	   }
	   else {
		   $clientName = $row['client_name'];
		     $clientAddress = $row['client_address'];

	   }
					$count++;
					
                    $output .= 
                    '<tr align="center">  
                        <td>'.$clientName.'</td>  
                        <td>'.$clientAddress.'</td> 
						<td>'.$row['machine_name'].' - '.$row['model'].'</td>						
                        <td>'.$row['schedule_date'].'</td>  
                        <td>'.$row['service_date'].'</td>
                        <td>'.$row['service_by'].'</td>
						 <td>'.$row['rep_problem'].'</td>
                     
                    </tr>';  
                }
					if($total > 0 && $output !='') {
					$output .= '<br><br>Resolved ';
		$percentage  = ( $count / $total)  * 100;
			$output.=$doc_name.': '.(int)$percentage.'%';

        }
            } elseif ($client != "null" && $service_by !="null") {
                $sql = "SELECT pms.schedule_id, pms.service_date, pms.service_by, pms.status, schedule.schedule_date, schedule.model,  schedule.guest, schedule.rep_problem, schedule.client_id, clients.client_name, schedule.machine_type, schedule.model, clients.client_address, machine_type.machine_name from (((pms inner join schedule on pms.schedule_id = schedule.schedule_id) left join clients on schedule.client_id = clients.client_id)
				left join machine_type on schedule.machine_type = machine_type.machine_id)where pms.service_date BETWEEN '$date_from' and '$date_to' AND schedule.contract_id ='' and clients.client_id = '$client' and pms.service_by = '$service_by'
				and schedule.status = '2' GROUP BY pms.schedule_id";  
                $result = mysqli_query($conn, $sql);  
                while($row = mysqli_fetch_array($result)) {
					$count++;
                    $output .= 
                   '<tr align="center">  
                         <td>'.$row['client_name'].'</td>  
                        <td>'.$row['client_address'].'</td> 
							<td>'.$row['machine_name'].' - '.$row['model'].'</td>						
                        <td>'.$row['schedule_date'].'</td>  
                        <td>'.$row['service_date'].'</td>
                        <td>'.$row['service_by'].'</td>
						 <td>'.$row['rep_problem'].'</td>
                    </tr>'; 
                }
            }
			elseif ($client != "null" && $service_by =="null") {
                $sql = "SELECT pms.schedule_id, pms.service_date, pms.service_by, pms.status, schedule.schedule_date, schedule.model, schedule.rep_problem,  schedule.guest, schedule.client_id, clients.client_name, schedule.machine_type, schedule.model, clients.client_address, machine_type.machine_name from (((pms inner join schedule on pms.schedule_id = schedule.schedule_id) left join clients on schedule.client_id = clients.client_id)
				left join machine_type on schedule.machine_type = machine_type.machine_id)  where pms.service_date BETWEEN '$date_from' and '$date_to' AND schedule.contract_id ='' and clients.client_id = '$client' and schedule.status = '2' GROUP BY pms.schedule_id";  
                $result = mysqli_query($conn, $sql);  
                while($row = mysqli_fetch_array($result)) {
					$count++;
                    $output .= 
                   '<tr align="center">  
                         <td>'.$row['client_name'].'</td>  
                        <td>'.$row['client_address'].'</td> 
						<td>'.$row['machine_name'].' - '.$row['model'].'</td>						
                        <td>'.$row['schedule_date'].'</td>  
                        <td>'.$row['service_date'].'</td>
                        <td>'.$row['service_by'].'</td>
						 <td>'.$row['rep_problem'].'</td>
                    </tr>'; 
                }
            }
			elseif ($client == "null" && $service_by !="null") {
                $sql = "SELECT pms.schedule_id, pms.service_date, pms.service_by, pms.status, schedule.schedule_date, schedule.model, schedule.rep_problem, schedule.guest, schedule.client_id, clients.client_name, schedule.machine_type, schedule.model, clients.client_address, machine_type.machine_name from (((pms inner join schedule on pms.schedule_id = schedule.schedule_id) left join clients on schedule.client_id = clients.client_id)
				left join machine_type on schedule.machine_type = machine_type.machine_id)   where pms.service_date BETWEEN '$date_from' and '$date_to' AND schedule.contract_id ='' and pms.service_by = '$service_by' and schedule.status = '2'  GROUP BY pms.schedule_id";  
                $result = mysqli_query($conn, $sql);  
                while($row = mysqli_fetch_array($result)) {
								 if ($row['guest']) {
		$guest = $row['guest'];
		 $last_space = strrpos($guest, ' / ');
$clientAddress = substr($guest, $last_space + 2);
$clientName = substr($guest, 0, $last_space);
	   }
	   else {
		   $clientName = $row['client_name'];
		     $clientAddress = $row['client_address'];

	   }
					$count++;
                    $output .= 
                   '<tr align="center">  
                         <td>'.$clientName.'</td>  
                        <td>'.$clientAddress.'</td> 
							<td>'.$row['machine_name'].' - '.$row['model'].'</td>						
                        <td>'.$row['schedule_date'].'</td>  
                        <td>'.$row['service_date'].'</td>
                        <td>'.$row['service_by'].'</td>
						<td>'.$row['rep_problem'].'</td>
                    </tr>'; 
                }
            }
		
	   }
	   elseif ($category == "Unresolved" ){
		
            if ($client == "null" &&   $service_by == "null") {
				
                $sql = "SELECT pms.schedule_id, pms.service_date, pms.service_by, pms.status, schedule.schedule_date,schedule.rep_problem, schedule.model,  schedule.guest, schedule.client_id, clients.client_name, schedule.machine_type, schedule.model, clients.client_address, machine_type.machine_name from (((pms inner join schedule on pms.schedule_id = schedule.schedule_id) left join clients on schedule.client_id = clients.client_id)
				left join machine_type on schedule.machine_type = machine_type.machine_id)  where pms.service_date BETWEEN '$date_from' and '$date_to' AND schedule.contract_id ='' and schedule.status = '3' GROUP BY pms.schedule_id ";  
                $result = mysqli_query($conn, $sql);  
                while($row = mysqli_fetch_array($result)) {
										 if ($row['guest']) {
		$guest = $row['guest'];
		 $last_space = strrpos($guest, ' / ');
$clientAddress = substr($guest, $last_space + 2);
$clientName = substr($guest, 0, $last_space);
	   }
	   else {
		   $clientName = $row['client_name'];
		     $clientAddress = $row['client_address'];

	   }
					
					$count++;
					
					
                    $output .= 
                    '<tr align="center">  
                        <td>'.$clientName.'</td>  
                        <td>'.$clientAddress.'</td> 
							<td>'.$row['machine_name'].' - '.$row['model'].'</td>						
                        <td>'.$row['schedule_date'].'</td>  
                        <td>'.$row['service_date'].'</td>
                        <td>'.$row['service_by'].'</td>
						 <td>'.$row['rep_problem'].'</td>
                     
                    </tr>';  
                }
			
            } elseif ($client != "null" && $service_by !="null") {
                $sql = "SELECT pms.schedule_id, pms.service_date, pms.service_by, pms.status, schedule.schedule_date, schedule.model,  schedule.rep_problem, schedule.guest, schedule.client_id, clients.client_name, schedule.machine_type, schedule.model, clients.client_address, machine_type.machine_name from (((pms inner join schedule on pms.schedule_id = schedule.schedule_id) left join clients on schedule.client_id = clients.client_id)
				left join machine_type on schedule.machine_type = machine_type.machine_id)  where pms.service_date BETWEEN '$date_from' and '$date_to' AND schedule.contract_id ='' and clients.client_id = '$client' and pms.service_by = '$service_by'
				and schedule.status = '3' GROUP BY pms.schedule_id";  
                $result = mysqli_query($conn, $sql);  
                while($row = mysqli_fetch_array($result)) {
					$count++;
                    $output .= 
                   '<tr align="center">  
                         <td>'.$row['client_name'].'</td>  
                        <td>'.$row['client_address'].'</td> 
							<td>'.$row['machine_name'].' - '.$row['model'].'</td>							
                        <td>'.$row['schedule_date'].'</td>  
                        <td>'.$row['service_date'].'</td>
                        <td>'.$row['service_by'].'</td>
						 <td>'.$row['rep_problem'].'</td>
                    </tr>'; 
                }
            }
			elseif ($client != "null" && $service_by =="null") {
                $sql = "SELECT pms.schedule_id, pms.service_date, pms.service_by, pms.status, schedule.schedule_date, schedule.rep_problem, schedule.model,  schedule.guest, schedule.client_id, clients.client_name, schedule.machine_type, schedule.model, clients.client_address, machine_type.machine_name from (((pms inner join schedule on pms.schedule_id = schedule.schedule_id) left join clients on schedule.client_id = clients.client_id)
				left join machine_type on schedule.machine_type = machine_type.machine_id) where pms.service_date BETWEEN '$date_from' and '$date_to' AND schedule.contract_id ='' and clients.client_id = '$client' and schedule.status = '3' GROUP BY pms.schedule_id ";  
                $result = mysqli_query($conn, $sql);  
                while($row = mysqli_fetch_array($result)) {
					$count++;
                    $output .= 
                   '<tr align="center">  
                         <td>'.$row['client_name'].'</td>  
                        <td>'.$row['client_address'].'</td> 
						<td>'.$row['machine_name'].' - '.$row['model'].'</td>								
                        <td>'.$row['schedule_date'].'</td>  
                        <td>'.$row['service_date'].'</td>
                        <td>'.$row['service_by'].'</td>
						 td>'.$row['rep_problem'].'</td>
                    </tr>'; 
                }
            }
			elseif ($client == "null" && $service_by !="null") {
                $sql = "SELECT pms.schedule_id, pms.service_date, pms.service_by, pms.status, schedule.schedule_date, schedule.model, schedule.rep_problem,   schedule.guest, schedule.client_id, clients.client_name, schedule.machine_type, schedule.model, clients.client_address, machine_type.machine_name from (((pms inner join schedule on pms.schedule_id = schedule.schedule_id) left join clients on schedule.client_id = clients.client_id)
				left join machine_type on schedule.machine_type = machine_type.machine_id)  where pms.service_date BETWEEN '$date_from' and '$date_to' AND schedule.contract_id ='' and pms.service_by = '$service_by' and schedule.status = '3' GROUP BY pms.schedule_id";  
                $result = mysqli_query($conn, $sql);  
                while($row = mysqli_fetch_array($result)) {
									 if ($row['guest']) {
		$guest = $row['guest'];
		 $last_space = strrpos($guest, ' / ');
$clientAddress = substr($guest, $last_space + 2);
$clientName = substr($guest, 0, $last_space);
	   }
	   else {
		   $clientName = $row['client_name'];
		     $clientAddress = $row['client_address'];

	   }
					$count++;
                    $output .= 
                   '<tr align="center">  
                         <td>'. $clientName.'</td>  
                        <td>'.$clientAddress.'</td> 
							<td>'.$row['machine_name'].' - '.$row['model'].'</td>							
                        <td>'.$row['schedule_date'].'</td>  
                        <td>'.$row['service_date'].'</td>
                        <td>'.$row['service_by'].'</td>
						 <td>'.$row['rep_problem'].'</td>
                    </tr>'; 
                }
            }
			
	   }
			
        }
		//Contract Status
        elseif ($table_name == "contract_status") {
			
            if ( $category == "Active" ) {
                $sql = "SELECT contract.client_id, contract.model, contract.status, contract.model, contract.turn_over, contract.coverage, clients.client_name,clients.client_address, machine_type.machine_name from ((contract left join clients on contract.client_id = clients.client_id) left join machine_type on contract.machine_type = machine_type.machine_id) where 
				contract.turn_over BETWEEN '$date_from' and '2023-01-01' and status != 'CONTRACT EXPIRED'; ";  
				 $result = mysqli_query($conn, $sql);  
                while($row = mysqli_fetch_array($result)) {
					$count++;
                    $output .= 
                    '<tr align="center">  
                        <td>'.$row['client_name'].'</td>  
                        <td>'.$row['client_address'].'</td> 
						<td>'.$row['machine_name'].' - '.$row['model'].'</td>		
						<td>'.$row['turn_over'].'</td>	
						<td>'.$row['coverage'].'</td>						
                      
                     
                    </tr>';  
                }
            } elseif ($category =="Expired") {
                $sql = "SELECT contract.client_id, contract.model, contract.status, contract.turn_over, contract.coverage, clients.client_name,clients.client_address, machine_type.machine_name from ((contract left join clients on contract.client_id = clients.client_id) left join machine_type on contract.machine_type = machine_type.machine_id) where status ='CONTRACT EXPIRED'; ";  
                $result = mysqli_query($conn, $sql);  
                while($row = mysqli_fetch_array($result)) {
                    $output .= 
                   '<tr align="center">  
                           <td>'.$row['client_name'].'</td>  
                        <td>'.$row['client_address'].'</td> 
						<td>'.$row['machine_name'].' - '.$row['model'].'</td>			
						<td>'.$row['turn_over'].'</td>	
						<td>'.$row['coverage'].'</td>	
                    </tr>'; 
                }
            }
	
				
        }
 //Service Done
		 elseif ($table_name == "service_done") {
		 
		
            if ($client == "null" &&   $service_by == "null") {
				
                $sql = "SELECT  pms.schedule_id, pms.service_problem,  pms.service_diagnosis,  pms.service_done,  pms.remarks, pms.service_date, pms.service_by, pms.status, schedule.schedule_date, schedule.model, schedule.guest, schedule.client_id, clients.client_name, machine_type.machine_name, clients.client_address from (((pms inner join schedule on pms.schedule_id = schedule.schedule_id) left join clients on schedule.client_id = clients.client_id)
				left join machine_type on schedule.machine_type = machine_type.machine_id) where pms.service_date BETWEEN '$date_from' and '$date_to'  ";  
                $result = mysqli_query($conn, $sql);  
                while($row = mysqli_fetch_array($result)) {
									 if ($row['guest']) {
		$guest = $row['guest'];
		 $last_space = strrpos($guest, ' / ');
$clientAddress = substr($guest, $last_space + 2);
$clientName = substr($guest, 0, $last_space);
	   }
	   else {
		   $clientName = $row['client_name'];
		     $clientAddress = $row['client_address'];

	   }
					$count++;
                    $output .= 
                    '<tr class="text-justify">  
                        <td>'. $clientName .'</td>  
                        <td>'. $clientAddress.'</td> 
						<td>'.$row['machine_name'].' - '.$row['model'].'</td>		
						<td>'.$row['service_problem'].'</td>
						<td>'.$row['service_diagnosis'].'</td>						
                        <td>'.$row['service_done'].'</td>
						<td>'.$row['remarks'].'</td>
						<td>'.$row['service_date'].'</td>
                        <td>'.$row['service_by'].'</td>
                     
                    </tr>';  
                }
            } elseif ($client != "null" && $service_by !="null") {
                $sql = "SELECT  pms.schedule_id, pms.service_problem,  pms.service_diagnosis,  pms.service_done,  pms.remarks, pms.service_date, pms.service_by, pms.status, schedule.schedule_date, schedule.model, schedule.guest, schedule.client_id, clients.client_name, clients.client_address, machine_type.machine_name from (((pms inner join schedule on pms.schedule_id = schedule.schedule_id) left join clients on schedule.client_id = clients.client_id)
				left join machine_type on schedule.machine_type = machine_type.machine_id) where pms.service_date BETWEEN '$date_from' and '$date_to' AND clients.client_id = '$client' and pms.service_by = '$service_by'
				and schedule.status = '2'";  
                $result = mysqli_query($conn, $sql);  
                while($row = mysqli_fetch_array($result)) {
					$count++;
                    $output .= 
                   '<tr class="text-justify">   
                        <td>'.$row['client_name'].'</td>  
                        <td>'.$row['client_address'].'</td> 
						<td>'.$row['model'].'</td>	
						<td>'.$row['service_problem'].'</td>
						<td>'.$row['service_diagnosis'].'</td>						
                        <td>'.$row['service_done'].'</td>
						<td>'.$row['remarks'].'</td>
						<td>'.$row['service_date'].'</td>
                        <td>'.$row['service_by'].'</td>
                    </tr>'; 
                }
            }
			elseif ($client != "null" && $service_by =="null") {
                $sql = "SELECT  pms.schedule_id, pms.service_problem,  pms.service_diagnosis,  pms.service_done,  pms.remarks, pms.service_date, pms.service_by, pms.status, schedule.schedule_date, schedule.model, schedule.guest, schedule.client_id, clients.client_name, clients.client_address, machine_type.machine_name from (((pms inner join schedule on pms.schedule_id = schedule.schedule_id) left join clients on schedule.client_id = clients.client_id)
				left join machine_type on schedule.machine_type = machine_type.machine_id) where pms.service_date BETWEEN '$date_from' and '$date_to' AND clients.client_id = '$client' ";  
                $result = mysqli_query($conn, $sql);  
                while($row = mysqli_fetch_array($result)) {
					
					$count++;
                    $output .= 
                   '<tr class="text-justify">    
                          <td>'.$row['client_name'].'</td>  
                        <td>'.$row['client_address'].'</td> 
						<td>'.$row['machine_name'].' - '.$row['model'].'</td>		
						<td>'.$row['service_problem'].'</td>
						<td>'.$row['service_diagnosis'].'</td>						
                        <td>'.$row['service_done'].'</td>
						<td>'.$row['remarks'].'</td>
						<td>'.$row['service_date'].'</td>
                        <td>'.$row['service_by'].'</td>
                    </tr>'; 
                }
            }
			elseif ($client == "null" && $service_by !="null") {
                $sql = "SELECT  pms.schedule_id, pms.service_problem,  pms.service_diagnosis,  pms.service_done,  pms.remarks, pms.service_date, pms.service_by, pms.status, schedule.schedule_date, schedule.model, schedule.guest, schedule.client_id, machine_type.machine_name, clients.client_name, clients.client_address from (((pms inner join schedule on pms.schedule_id = schedule.schedule_id) left join clients on schedule.client_id = clients.client_id)
				left join machine_type on schedule.machine_type = machine_type.machine_id) where pms.service_date BETWEEN '$date_from' and '$date_to' AND pms.service_by = '$service_by'  ";  
                $result = mysqli_query($conn, $sql);  
                while($row = mysqli_fetch_array($result)) {
							 if ($row['guest']) {
		$guest = $row['guest'];
		 $last_space = strrpos($guest, ' / ');
$clientAddress = substr($guest, $last_space + 2);
$clientName = substr($guest, 0, $last_space);
	   }
	   else {
		   $clientName = $row['client_name'];
		     $clientAddress = $row['client_address'];

	   }
		
					$count++;
                    $output .= 
                   '<tr class="text-justify">  
                           <td>'. $clientName .'</td>  
                        <td>'.$clientAddress .'</td> 
							<td>'.$row['machine_name'].' - '.$row['model'].'</td>		
						<td>'.$row['service_problem'].'</td>
						<td>'.$row['service_diagnosis'].'</td>						
                        <td>'.$row['service_done'].'</td>
						<td>'.$row['remarks'].'</td>
						<td>'.$row['service_date'].'</td>
                        <td>'.$row['service_by'].'</td>
                    </tr>'; 
                }
            }
	   
	   
		
        }
    
        return $output;  
    }  
	
    if(isset($_POST["create_pdf"])) {  
        $doc_name = $_POST['doc_name'];
        $doc_type = $_POST['doc_type'];
			$datefilter = $_POST['datefilter'];
		$date_to = $_POST['date_to'];
		$date_to_temp = $_POST['date_to_temp'];
		$date_from_temp = $_POST['date_from_temp'];
		$date_from = $_POST['date_from'];
        $table_name = $_POST['doc_type'];
		  $category = $_POST['category'];
        $firstname= $_SESSION['firstname'];
        $lastname= $_SESSION['lastname'];
		$report_name = $_POST['report_name']; 
		$report_date =date("Y-m-d");
		$pms_type = $doc_type.' '.$category;
	
         /// PDF
      /// PDF
        $obj_pdf = new MYPDF('L', 'mm', 'A4'); 
        $obj_pdf->SetCreator(PDF_CREATOR);  
        $obj_pdf->SetTitle($doc_name);  
        $obj_pdf->SetHeaderData('', '', PDF_HEADER_TITLE, PDF_HEADER_STRING);
        
        // set header and footer fonts  
        $obj_pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));  
        $obj_pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA)); 
        
        // set default monospaced font
        $obj_pdf->SetDefaultMonospacedFont('helvetica');

        // set margins
        $obj_pdf->SetFooterMargin(10);
        $obj_pdf->SetMargins(PDF_MARGIN_LEFT, '11', PDF_MARGIN_RIGHT);  
        $obj_pdf->setPrintHeader(false); 
        $obj_pdf->SetAutoPageBreak(TRUE, 17);

        $obj_pdf->SetFont('helvetica', '', 12); 

        // set auto page breaks
        $obj_pdf->AddPage(); 
        $content = '';
    
        /// PDF style
        $content .= '
            <style>
                th {
                    background-color: #ccc;
                   
                }

            </style>
            <div class="header">';
                $obj_pdf -> Image('../image/icon.jpg', 105, 10, 27);
              
                $obj_pdf -> SetFont('Helvetica', 'B', 14);
                $obj_pdf -> Cell(287, 7, "KVP Health Care Inc.", 0, 1, 'C');
                $obj_pdf -> SetFont('Helvetica', 'B', 12);
                $obj_pdf -> Cell(287, 6, "Biñan, Laguna", 0, 1, 'C');
                $obj_pdf -> SetFont('Helvetica', '', 12);
               
                $obj_pdf -> Ln(13);
             
                $obj_pdf -> SetFont('Helvetica', '', 12);
                $obj_pdf -> Cell(277, 7, "$category $doc_name", 0, 1, 'C');
                $obj_pdf -> SetFont('Helvetica', '', 12);
				if ($datefilter!="null") {
                $obj_pdf -> Cell(277, 7, "Date: $date_from_temp - $date_to_temp", 0, 0, 'C');
				}
                $obj_pdf -> Ln(7);
                $obj_pdf -> SetFont('Helvetica', '', 11);
				
                $content .= ' 
            </div>
            <table border="0" cellspacing="0" cellpadding="5">';
            if ($table_name =='res_pms'  && $category =='Attended') {		
                $content .= '
                <tr align="center">
                    <th width="20%">Client Name</th>  
                    <th width="20%">Address</th>  
                    <th width="15%">Machine</th>  
                    <th width="15%">Schedule Date</th>
                    <th width="15%">Service Date</th>
                    <th width="15%">Service By</th>
					</tr>'; 
					}
					 if ($table_name =='res_pms' && $category =='Unattended') {		
                $content .= '
                <tr align="center">
                    <th width="25%">Client Name</th>  
                    <th width="25%">Address</th>  
                    <th width="25%">Machine</th>  
                    <th width="25%">Schedule Date</th>
              
					</tr>'; 
					}
					  
	if ($table_name =='svc') {
                $content .= '
                <tr align="center">
                  <th>Client Name</th>  
                    <th>Address</th>  
                    <th >Machine</th>  
                    <th>Schedule Date</th>
                    <th >Service Date</th>
                    <th>Service By</th>	
					<th>Reported Problem</th>	
                </tr>';
            } 
			 
			
			
			if ($table_name =='contract_status') {
                $content .= '
                <tr align="center">
                  <th width="20%">Client Name</th>  
                    <th width="20%">Address</th>  
                    <th width="20%">Machine</th>
					 <th width="20%">Turn Over</th>
                    <th width="20%">Coverage</th>
					
					
                   
                </tr>';
            }
				
			if ($table_name =='service_done') {
                $content .= '
                <tr align="center">
                  <th width="11%">Client Name</th>  
                    <th width="11%">Address</th>  
                    <th width="11%">Machine</th>
					<th width="11%">Reported Problem</th>
					<th width="11%">Diagnosis</th>
				    <th width="11%">Work Done</th>
					<th width="11%">Recommendation</th>
						 <th width="11%">Date of Service</th>		
<th width="11%">Serviced By</th>						 
       
                </tr>';
            }
			
        $content .= fetch_data(); 
        $content .= '</table>';  	
		include ('../inc/dbc.inc.php');
			$location = "../inc/files/".$report_name.'.pdf';
			$sql2= "INSERT INTO `report` (`report_id`, `location`, `report_name`, `report_date`, `generated_by`) VALUES (NULL, '$location', '$report_name.pdf', '$report_date', '$firstname $lastname')";
		$result2 = $conn->query($sql2);
		$notif_user = $_SESSION['id'];
	$notif_name = $_SESSION['firstname'];
	$notif_desc = $notif_name." generated a report ".$report_name.".pdf";
	$notif_date =date("Y-m-d H:i:s");
	
        $obj_pdf->writeHTML($content); 
		$obj_pdf->Output(__DIR__ . '/files/'.$report_name.'.pdf', 'F');
        $obj_pdf->Output($report_name.'.pdf', 'I');
			
		
    } 
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Export Table Data to PDF</title>  
    <?php include '../inc/sources.php'; ?>
</head>
<body>
    <section>
        <?php 
            require_once '../inc/dbc.inc.php';
			$firstname = $_SESSION['firstname'];
			$lastname = $_SESSION['lastname'];
			$doc_name = $_POST['doc_name'];
			$report_name = $_POST['report_name'];
			$category = $_POST['category'];
				$datefilter = $_POST['datefilter'];
				$string=$datefilter;
				$last_space = strrpos($string, ' ');
				$last_word = substr($string, $last_space);
				$first_chunk = substr($string, 0, $last_space - 2);
			$date_to = date('Y-m-d', strtotime($last_word));
			$date_to_temp = date('d F Y', strtotime($date_to));
			$date_from_temp = date('d F Y', strtotime($first_chunk));
	$date_from = date('Y-m-d', strtotime($first_chunk));
			$client_id = $_POST['client_id'];
			$service_by = $_POST['service_by'];
			$table_name= $_POST['doc_type'];
			$doc_type= $_POST['doc_type'];
			
			
			
			
        ?>
        <div class="container mt-5" style="width:1200px;">  
            <div class="header">
                <h3 class="text-center"><?php echo $category." ".$doc_name; ?></h3>
				<?php if($datefilter!='null') { ?>
                <h6 class="text-center">Date: <?php echo $date_from_temp; ?> - <?php echo $date_to_temp; ?></h6>
				<?php } ?>
            </div>
            <br />  
            <div class="table-responsive">  
                 <table class="table table-bordered table-striped">  
                    <?php
                        if ($table_name == "res_pms") {
								if($category =="Attended") {
                            echo "<tr>  
                               <th class='text-center' width='20%'>Client</th>  
                    <th class='text-center' width='20%'>Address</th>  
                    <th class='text-center' width='15%'>Machine</th>  
                    <th class='text-center' width='15%'>Schedule Date</th>
                    <th class='text-center' width='15%'>Service Date</th>
                    <th class='text-center' width='15%'> Service By</th>
                            </tr>";
								}
									elseif($category =="Unattended") {
                            echo "<tr>  
                               <th class='text-center' width='20%'>Client</th>  
                    <th class='text-center' width='20%'>Address</th>  
                    <th class='text-center' width='15%'>Machine</th>  
                    <th class='text-center' width='15%'>Schedule Date</th>
					
               
                            </tr>";
								}
						} elseif ($table_name == "svc") {
                            echo "
                            <tr>
                              <th class='text-center' width='20%'>Client</th>  
                    <th class='text-center'>Address</th>  
                    <th class='text-center' >Machine</th>  
                    <th class='text-center' >Schedule Date</th>
                    <th class='text-center' >Service Date</th>
                    <th class='text-center' > Service By</th>
					<th class='text-center' >Reported Problem</th>
                            </tr>";
                        } elseif ($table_name == "contract_status") {
                            echo "
                            <tr>
                    <th class='text-center' width='20%'>Client</th>  
                    <th class='text-center' width='20%'>Address</th>  
                    <th class='text-center' width='20%'>Machine</th> 
                    <th class='text-center' width='20%'>Turn Over</th>  	
						<th class='text-center' width='20%'>Coverage</th> 					
                   
                            </tr>";
                        } elseif ($table_name == "service_done") {
                            echo "
                            <tr class='text-left'>
                               <th width='11%'>Client Name</th>  
                    <th width='11%'>Address</th>  
                    <th width='11%'>Machine</th>
					<th width='11%'>Reported Problem</th>
					<th width='11%'>Diagnosis</th>
				    <th width='11%'>Work Done</th>
					<th width='11%'>Recommendation</th>
						 <th width='11%'>Date of Service</th>		
<th width='11%'>Serviced By</th>	
                            </tr>";
                        } elseif ($table_name == "proposal_module") {
                            echo "
                            <tr>
                                <th class='text-center' width='10%'>ID</th>  
                                <th class='text-center' width='30%'>File Name</th>  
                                <th class='text-center' width='30%'>Agenda</th>  
                                <th class='text-center' width='30%'>Uploaded Date</th>
                            </tr>";
                        } elseif ($table_name == "other") {
                            echo "
                            <tr>
                                <th class='text-center' width='10%'>ID</th>  
                                <th class='text-center' width='30%'>File Name</th>  
                                <th class='text-center' width='30%'>Description</th>  
                                <th class='text-center' width='30%'>Uploaded Date</th>
                            </tr>";
                        } elseif ($table_name == "extension") {
                            echo "
                            <tr>
                                <th class='text-center' width='10%'>ID</th>  
								<th class='text-center' width='20%'>Extension Activity</th>  
                                <th class='text-center' width='30%'>File Name</th>  
                                <th class='text-center' width='20%'>Description</th>  
                                <th class='text-center' width='20%'>Extension Date</th>
                            </tr>";
                        }
                    ?>
                 <?php  
                    echo fetch_data();  
                 ?> 
                 </table>
                 <h6 class="text-right">Generated by: <?php echo $firstname; echo " "; echo $lastname;?></h6>
                 <div class="form-group text-center">
                    <form method="post">
                        <input type="hidden" name="doc_type" value="<?php echo $doc_type; ?>">
                        <input type="hidden" name="doc_name" value="<?php echo $doc_name; ?>">
						 <input type="hidden" name="datefilter" value="<?php echo $datefilter; ?>">
                        <input type="hidden" name="date_from" value="<?php echo $date_from;?>">
                        <input type="hidden" name="date_from_temp" value="<?php echo $date_from_temp;?>">
                        <input type="hidden" name="date_to" value="<?php echo $date_to; ?>">
                        <input type="hidden" name="date_to_temp" value="<?php echo $date_to_temp; ?>">
                        <input type="hidden" name="client_id" value="<?php echo $client_id; ?>">
                        <input type="hidden" name="service_by" value="<?php echo $service_by; ?>">          
						  <input type="hidden" name="report_name" value="<?php echo $report_name; ?>">
						   <input type="hidden" name="category" value="<?php echo $category; ?>">
                        <button type="submit" name="create_pdf" class="btn btn-danger">
                              <span>Create PDF</span>
                        </button> 
                    </form>
                 </div>
            </div>  
        </div>
    </section>
</body>
</html>